module.exports = {
  "var(--antd-wave-shadow-color)": "#1890FF",
  "var(--fade-primary-color-20)": "rgba(24, 144, 255, 0.2)",
  "var(--fade-radio-dot-color-6)": "rgba(24, 144, 255, 0.06)",
  "var(--fade-radio-dot-color-8)": "rgba(24, 144, 255, 0.08)",
  "var(--fade-card-skeleton-bg-20)": "rgba(207, 216, 220, 0.2)",
  "var(--fade-card-skeleton-bg-40)": "rgba(207, 216, 220, 0.4)",
  "var(--fade-switch-color-20)": "rgba(24, 144, 255, 0.2)",
  "var(--shade-text-color-secondary-40)": "rgba(0, 0, 0, 0.67)",
  "var(--shade-skeleton-color-5)": "#e6e6e6",
  "var(--darken-disabled-bg-10)": "#dbdbdb",
  "var(--darken-table-header-bg-3)": "#f7f7f7",
  "var(--darken-table-header-bg-3-5)": "#ebebeb",
  "var(--tabs-horizontal-padding-extract-1)": "12px",
  "var(--tabs-horizontal-padding-lg-extract-1)": "16px",
  "var(--tabs-horizontal-padding-sm-extract-1)": "8px",
  "var(--tint-layout-sider-background-10)": "#192c3e",
  "var(--primary-color)": "#1890ff",
  "var(--primary-1)": "#e6f7ff",
  "var(--primary-2)": "#bae7ff",
  "var(--primary-3)": "#91d5ff",
  "var(--primary-4)": "#69c0ff",
  "var(--primary-5)": "#40a9ff",
  "var(--primary-6)": "#1890FF",
  "var(--primary-7)": "#096dd9",
  "var(--primary-8)": "#0050b3",
  "var(--primary-9)": "#003a8c",
  "var(--primary-10)": "#002766",
  "var(--info-color)": "#1890ff",
  "var(--success-color)": "#52c41a",
  "var(--processing-color)": "#1890ff",
  "var(--error-color)": "#f5222d",
  "var(--error-1)": "#fff1f0",
  "var(--error-2)": "#ffccc7",
  "var(--error-3)": "#ffa39e",
  "var(--error-4)": "#ff7875",
  "var(--error-5)": "#ff4d4f",
  "var(--error-6)": "#f5222d",
  "var(--error-7)": "#cf1322",
  "var(--error-8)": "#a8071a",
  "var(--error-9)": "#820014",
  "var(--error-10)": "#5c0011",
  "var(--highlight-color)": "#f5222d",
  "var(--warning-color)": "#faad14",
  "var(--warning-1)": "#fffbe6",
  "var(--warning-2)": "#fff1b8",
  "var(--warning-3)": "#ffe58f",
  "var(--warning-4)": "#ffd666",
  "var(--warning-5)": "#ffc53d",
  "var(--warning-6)": "#faad14",
  "var(--warning-7)": "#d48806",
  "var(--warning-8)": "#ad6800",
  "var(--warning-9)": "#874d00",
  "var(--warning-10)": "#613400",
  "var(--normal-color)": "#d9d9d9",
  "var(--scrollbar-color)": "#d9d9d9",
  "var(--scrollbar-size)": "10px",
  "var(--scrollbar-border-radius)": "0",
  "var(--body-background)": "#fff",
  "var(--component-background)": "#fff",
  "var(--font-family)": "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', 'Helvetica Neue', Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'",
  "var(--code-family)": "'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, Courier, monospace",
  "var(--text-color)": "rgba(0, 0, 0, 0.65)",
  "var(--text-color-1)": "rgba(0, 0, 0, 0.1)",
  "var(--text-color-2)": "rgba(0, 0, 0, 0.2)",
  "var(--text-color-3)": "rgba(0, 0, 0, 0.3)",
  "var(--text-color-4)": "rgba(0, 0, 0, 0.4)",
  "var(--text-color-5)": "rgba(0, 0, 0, 0.5)",
  "var(--text-color-6)": "rgba(0, 0, 0, 0.6)",
  "var(--text-color-7)": "rgba(0, 0, 0, 0.7)",
  "var(--text-color-8)": "rgba(0, 0, 0, 0.8)",
  "var(--text-color-9)": "rgba(0, 0, 0, 0.9)",
  "var(--text-color-10)": "#000000",
  "var(--text-color-secondary)": "rgba(0, 0, 0, 0.45)",
  "var(--text-color-inverse)": "#fff",
  "var(--icon-color)": "inherit",
  "var(--icon-color-hover)": "rgba(0, 0, 0, 0.75)",
  "var(--heading-color)": "rgba(0, 0, 0, 0.85)",
  "var(--heading-color-dark)": "#ffffff",
  "var(--text-color-dark)": "rgba(255, 255, 255, 0.85)",
  "var(--text-color-secondary-dark)": "rgba(255, 255, 255, 0.65)",
  "var(--text-selection-bg)": "#1890FF",
  "var(--font-variant-base)": "tabular-nums",
  "var(--font-feature-settings-base)": "'tnum'",
  "var(--font-size-base)": "12px",
  "var(--font-size-lg)": "12px + 2px",
  "var(--font-size-sm)": "12px",
  "var(--heading-1-size)": "33px",
  "var(--heading-2-size)": "26px",
  "var(--heading-3-size)": "21px",
  "var(--heading-4-size)": "18px",
  "var(--line-height-base)": "1.5",
  "var(--border-radius-base)": "4px",
  "var(--border-radius-sm)": "2px",
  "var(--padding-lg)": "24px",
  "var(--padding-md)": "16px",
  "var(--padding-sm)": "12px",
  "var(--padding-xs)": "8px",
  "var(--control-padding-horizontal)": "12px",
  "var(--control-padding-horizontal-sm)": "8px",
  "var(--item-active-bg)": "#e6f7ff",
  "var(--item-hover-bg)": "#e6f7ff",
  "var(--item-hover-color)": "#000",
  "var(--link-color)": "#1890FF",
  "var(--link-hover-color)": "#40a9ff",
  "var(--link-active-color)": "#096dd9",
  "var(--link-decoration)": "none",
  "var(--link-hover-decoration)": "none",
  "var(--border-color-base)": "#d9d9d9",
  "var(--border-color-split)": "#e8e8e8",
  "var(--border-color-inverse)": "#fff",
  "var(--border-width-base)": "1px",
  "var(--border-style-base)": "solid",
  "var(--outline-blur-size)": "0",
  "var(--outline-width)": "2px",
  "var(--outline-color)": "#1890FF",
  "var(--background-color-light)": "#fafafa",
  "var(--background-color-base)": "#f5f5f5",
  "var(--disabled-color)": "rgba(0, 0, 0, 0.25)",
  "var(--disabled-bg)": "#f5f5f5",
  "var(--disabled-color-dark)": "rgba(255, 255, 255, 0.35)",
  "var(--shadow-color)": "rgba(0, 0, 0, 0.15)",
  "var(--shadow-color-inverse)": "#fff",
  "var(--box-shadow-base)": "0 2px 8px rgba(0, 0, 0, 0.15)",
  "var(--shadow-1-up)": "0 -2px 8px rgba(0, 0, 0, 0.15)",
  "var(--shadow-1-down)": "0 2px 8px rgba(0, 0, 0, 0.15)",
  "var(--shadow-1-left)": "-2px 0 8px rgba(0, 0, 0, 0.15)",
  "var(--shadow-1-right)": "2px 0 8px rgba(0, 0, 0, 0.15)",
  "var(--shadow-2)": "0 4px 12px rgba(0, 0, 0, 0.15)",
  "var(--btn-font-weight)": "400",
  "var(--btn-border-radius-base)": "4px",
  "var(--btn-border-radius-sm)": "4px",
  "var(--btn-border-width)": "1px",
  "var(--btn-border-style)": "solid",
  "var(--btn-shadow)": "0 2px 0 rgba(0, 0, 0, 0.015)",
  "var(--btn-primary-shadow)": "0 2px 0 rgba(0, 0, 0, 0.045)",
  "var(--btn-text-shadow)": "0 -1px 0 rgba(0, 0, 0, 0.12)",
  "var(--btn-primary-color)": "#1890FF",
  "var(--btn-primary-bg)": "#fff",
  "var(--btn-default-color)": "rgba(0, 0, 0, 0.5)",
  "var(--btn-default-bg)": "#fff",
  "var(--btn-default-border-color)": "rgba(0, 0, 0, 0.2)",
  "var(--btn-warning-color)": "#ffc53d",
  "var(--btn-warning-bg)": "#fff",
  "var(--btn-warning-border)": "#ffc53d",
  "var(--btn-danger-color)": "#ff4d4f",
  "var(--btn-danger-bg)": "#fff",
  "var(--btn-danger-border)": "#ff4d4f",
  "var(--btn-disable-color)": "rgba(0, 0, 0, 0.25)",
  "var(--btn-disable-bg)": "#f5f5f5",
  "var(--btn-disable-border)": "#d9d9d9",
  "var(--btn-padding-base)": "0 15px",
  "var(--btn-font-size-lg)": "14px",
  "var(--btn-font-size-sm)": "12px",
  "var(--btn-padding-lg)": "0 15px",
  "var(--btn-padding-sm)": "0 15px",
  "var(--btn-height-base)": "32px",
  "var(--btn-height-lg)": "40px",
  "var(--btn-height-sm)": "24px",
  "var(--btn-circle-size)": "32px",
  "var(--btn-circle-size-lg)": "40px",
  "var(--btn-circle-size-sm)": "24px",
  "var(--btn-square-size)": "32px",
  "var(--btn-square-size-lg)": "40px",
  "var(--btn-square-size-sm)": "24px",
  "var(--btn-group-border)": "#40a9ff",
  "var(--checkbox-size)": "16px",
  "var(--checkbox-color)": "#1890FF",
  "var(--checkbox-check-color)": "#fff",
  "var(--checkbox-border-width)": "1px",
  "var(--descriptions-bg)": "#fafafa",
  "var(--dropdown-selected-color)": "#1890FF",
  "var(--empty-font-size)": "12px",
  "var(--radio-size)": "16px",
  "var(--radio-dot-color)": "#1890FF",
  "var(--radio-dot-size)": "8px",
  "var(--radio-button-bg)": "#fff",
  "var(--radio-button-checked-bg)": "#fff",
  "var(--radio-button-color)": "#000",
  "var(--radio-button-hover-color)": "#40a9ff",
  "var(--radio-button-active-color)": "#096dd9",
  "var(--layout-body-background)": "#f0f2f5",
  "var(--layout-header-background)": "#001529",
  "var(--layout-footer-background)": "#f0f2f5",
  "var(--layout-header-height)": "40px",
  "var(--layout-header-padding)": "0 50px",
  "var(--layout-footer-padding)": "24px 50px",
  "var(--layout-sider-background)": "#fff",
  "var(--layout-trigger-height)": "48px",
  "var(--layout-trigger-background)": "#002140",
  "var(--layout-trigger-color)": "#fff",
  "var(--layout-zero-trigger-width)": "36px",
  "var(--layout-zero-trigger-height)": "42px",
  "var(--nav-header-height)": "40px",
  "var(--layout-sider-background-light)": "#fff",
  "var(--layout-trigger-background-light)": "#fff",
  "var(--layout-trigger-color-light)": "#000",
  "var(--collapse-panel-border-radius)": "4px",
  "var(--dropdown-vertical-padding)": "5px",
  "var(--dropdown-font-size)": "12px",
  "var(--dropdown-line-height)": "22px",
  "var(--label-required-color)": "#f5222d",
  "var(--label-color)": "rgba(0, 0, 0, 0.65)",
  "var(--form-warning-input-bg)": "#fff",
  "var(--form-item-margin-bottom)": "24px",
  "var(--form-item-trailing-colon)": "true",
  "var(--form-vertical-label-padding)": "0 0 0px 0px",
  "var(--form-vertical-label-margin)": "0",
  "var(--form-error-input-bg)": "#fff",
  "var(--form-component-height)": "32px",
  "var(--form-component-max-height)": "40px",
  "var(--form-feedback-icon-size)": "12px",
  "var(--form-help-margin-top)": "(32px - 40px) / 2 + 2px",
  "var(--form-explain-font-size)": "12px",
  "var(--form-explain-precision)": "1px",
  "var(--form-explain-height)": "18px",
  "var(--input-height-base)": "32px",
  "var(--input-height-lg)": "40px",
  "var(--input-height-sm)": "24px",
  "var(--input-padding-horizontal)": "calc(12px - 1px)",
  "var(--input-padding-horizontal-base)": "11px",
  "var(--input-padding-horizontal-sm)": "calc(8px - 1px)",
  "var(--input-padding-horizontal-lg)": "11px",
  "var(--input-padding-vertical-base)": "4px",
  "var(--input-padding-vertical-sm)": "1px",
  "var(--input-padding-vertical-lg)": "6px",
  "var(--input-placeholder-color)": "#bfbfbf",
  "var(--input-color)": "#000",
  "var(--input-border-color)": "#d9d9d9",
  "var(--input-border-bottom-color)": "#d9d9d9",
  "var(--input-border-hover-color)": "#1890FF",
  "var(--input-border-focus-color)": "#1890FF",
  "var(--input-border-focus-box-shadow)": "0 1px 1px rgba(0, 0, 0, 0)",
  "var(--input-border-radius)": "4px",
  "var(--input-bg)": "#fff",
  "var(--input-number-handler-active-bg)": "#f4f4f4",
  "var(--input-number-handler-hover-bg)": "#40a9ff",
  "var(--input-number-handler-bg)": "#fff",
  "var(--input-number-handler-border-color)": "#d9d9d9",
  "var(--input-addon-bg)": "#fff",
  "var(--input-hover-border-color)": "#40a9ff",
  "var(--input-disabled-bg)": "#f5f5f5",
  "var(--input-outline-offset)": "0 0",
  "var(--input-affix-width)": "20px",
  "var(--select-border-color)": "#d9d9d9",
  "var(--select-item-selected-font-weight)": "600",
  "var(--select-dropdown-bg)": "#fff",
  "var(--select-item-selected-bg)": "#fff",
  "var(--select-item-active-bg)": "#e6f7ff",
  "var(--anchor-border-color)": "#e8e8e8",
  "var(--tooltip-max-width)": "250px",
  "var(--tooltip-color)": "#fff",
  "var(--tooltip-bg)": "rgba(0, 0, 0, 0.75)",
  "var(--tooltip-arrow-width)": "5px",
  "var(--tooltip-distance)": "calc(5px - 1px + 4px)",
  "var(--tooltip-arrow-color)": "rgba(0, 0, 0, 0.75)",
  "var(--tooltip-arrow-shadow-width)": "5px",
  "var(--tooltip-arrow-rotate-width)": "16px",
  "var(--popover-bg)": "#fff",
  "var(--popover-color)": "#000",
  "var(--popover-min-width)": "177px",
  "var(--popover-arrow-width)": "6px",
  "var(--popover-arrow-color)": "#fff",
  "var(--popover-arrow-outer-color)": "#fff",
  "var(--popover-distance)": "calc(6px + 4px)",
  "var(--modal-body-padding)": "24px",
  "var(--modal-footer-bg)": "transparent",
  "var(--modal-footer-border-color-split)": "#e8e8e8",
  "var(--modal-mask-bg)": "rgba(0, 0, 0, 0.45)",
  "var(--modal-header-bg)": "#fff",
  "var(--modal-header-color)": "#000",
  "var(--modal-header-hover-color)": "#000000",
  "var(--progress-default-color)": "#1890ff",
  "var(--progress-remaining-color)": "#f5f5f5",
  "var(--progress-text-color)": "#000",
  "var(--progress-radius)": "100px",
  "var(--menu-inline-toplevel-item-height)": "40px",
  "var(--menu-item-height)": "40px",
  "var(--menu-collapsed-width)": "40px",
  "var(--menu-bg)": "#fff",
  "var(--menu-popup-bg)": "#fff",
  "var(--menu-item-color)": "#000",
  "var(--menu-item-dark-color)": "rgba(255, 255, 255, 0.8)",
  "var(--menu-highlight-color)": "#1890FF",
  "var(--menu-item-active-bg)": "#e6f7ff",
  "var(--menu-item-active-border-width)": "3px",
  "var(--menu-item-group-title-color)": "rgba(0, 0, 0, 0.45)",
  "var(--menu-item-vertical-margin)": "0px",
  "var(--menu-item-font-size)": "12px",
  "var(--menu-item-boundary-margin)": "8px",
  "var(--menu-icon-size)": "12px",
  "var(--menu-icon-size-lg)": "14px",
  "var(--dark-menu-item-hover-bg)": "transparent",
  "var(--menu-dark-color)": "rgba(255, 255, 255, 0.65)",
  "var(--menu-dark-bg)": "#001529",
  "var(--menu-dark-arrow-color)": "#fff",
  "var(--menu-dark-submenu-bg)": "#000c17",
  "var(--menu-dark-highlight-color)": "#fff",
  "var(--menu-dark-item-active-bg)": "#1890FF",
  "var(--menu-dark-selected-item-icon-color)": "#fff",
  "var(--menu-dark-selected-item-text-color)": "#fff",
  "var(--menu-dark-item-hover-bg)": "transparent",
  "var(--spin-dot-size-sm)": "14px",
  "var(--spin-dot-size)": "20px",
  "var(--spin-dot-size-lg)": "32px",
  "var(--table-header-bg)": "#fff",
  "var(--table-header-color)": "rgba(0, 0, 0, 0.85)",
  "var(--table-header-sort-bg)": "#f5f5f5",
  "var(--table-body-sort-bg)": "rgba(0, 0, 0, 0.01)",
  "var(--table-row-hover-bg)": "#e6f7ff",
  "var(--table-selected-row-color)": "inherit",
  "var(--table-selected-row-bg)": "#fafafa",
  "var(--table-body-selected-sort-bg)": "#fafafa",
  "var(--table-selected-row-hover-bg)": "#fafafa",
  "var(--table-expanded-row-bg)": "#fbfbfb",
  "var(--table-padding-vertical)": "16px",
  "var(--table-padding-horizontal)": "16px",
  "var(--table-border-radius-base)": "4px",
  "var(--table-footer-bg)": "#fff",
  "var(--table-footer-color)": "rgba(0, 0, 0, 0.85)",
  "var(--table-padding-vertical-md)": "16px * 3 / 4",
  "var(--table-padding-horizontal-md)": "16px / 2",
  "var(--table-padding-vertical-sm)": "16px / 2",
  "var(--table-padding-horizontal-sm)": "16px / 2",
  "var(--tag-default-bg)": "#fff",
  "var(--tag-default-color)": "#000",
  "var(--tag-font-size)": "12px",
  "var(--time-picker-panel-column-width)": "56px",
  "var(--time-picker-panel-width)": "56px * 3",
  "var(--time-picker-selected-bg)": "#f5f5f5",
  "var(--carousel-dot-width)": "16px",
  "var(--carousel-dot-height)": "3px",
  "var(--carousel-dot-active-width)": "24px",
  "var(--badge-height)": "20px",
  "var(--badge-dot-size)": "6px",
  "var(--badge-font-size)": "12px",
  "var(--badge-font-weight)": "normal",
  "var(--badge-status-size)": "6px",
  "var(--badge-text-color)": "#fff",
  "var(--rate-star-color)": "#fadb14",
  "var(--rate-star-bg)": "#e8e8e8",
  "var(--card-head-color)": "rgba(0, 0, 0, 0.85)",
  "var(--card-head-background)": "transparent",
  "var(--card-head-padding)": "16px",
  "var(--card-inner-head-padding)": "12px",
  "var(--card-padding-base)": "10px",
  "var(--card-actions-background)": "#fff",
  "var(--card-skeleton-bg)": "#cfd8dc",
  "var(--card-background)": "#fff",
  "var(--card-box-shadow)": "0 2px 8px rgba(0, 0, 0, 0.09)",
  "var(--card-border-radius)": "2px",
  "var(--comment-padding-base)": "16px 0",
  "var(--comment-nest-indent)": "44px",
  "var(--comment-font-size-base)": "12px",
  "var(--comment-font-size-sm)": "12px",
  "var(--comment-author-name-color)": "rgba(0, 0, 0, 0.45)",
  "var(--comment-author-time-color)": "#ccc",
  "var(--comment-action-color)": "rgba(0, 0, 0, 0.45)",
  "var(--comment-action-hover-color)": "#595959",
  "var(--tabs-card-head-background)": "#fff",
  "var(--tabs-card-height)": "40px",
  "var(--tabs-card-active-color)": "#1890FF",
  "var(--tabs-title-font-size)": "12px",
  "var(--tabs-title-font-size-lg)": "14px",
  "var(--tabs-title-font-size-sm)": "12px",
  "var(--tabs-ink-bar-color)": "#1890FF",
  "var(--tabs-bar-margin)": "0 0 16px 0",
  "var(--tabs-horizontal-margin)": "0 32px 0 0",
  "var(--tabs-horizontal-padding)": "12px 16px",
  "var(--tabs-horizontal-padding-lg)": "16px",
  "var(--tabs-horizontal-padding-sm)": "8px 16px",
  "var(--tabs-vertical-padding)": "8px 24px",
  "var(--tabs-vertical-margin)": "0 0 16px 0",
  "var(--tabs-scrolling-size)": "32px",
  "var(--tabs-highlight-color)": "#1890FF",
  "var(--tabs-hover-color)": "#40a9ff",
  "var(--tabs-active-color)": "#096dd9",
  "var(--tabs-card-gutter)": "2px",
  "var(--tabs-card-tab-active-border-top)": "2px solid transparent",
  "var(--back-top-color)": "#fff",
  "var(--back-top-bg)": "rgba(0, 0, 0, 0.45)",
  "var(--back-top-hover-bg)": "#000",
  "var(--avatar-size-base)": "32px",
  "var(--avatar-size-lg)": "40px",
  "var(--avatar-size-sm)": "24px",
  "var(--avatar-font-size-base)": "18px",
  "var(--avatar-font-size-lg)": "24px",
  "var(--avatar-font-size-sm)": "14px",
  "var(--avatar-bg)": "#fff",
  "var(--avatar-color)": "#fff",
  "var(--avatar-border-radius)": "4px",
  "var(--switch-height)": "22px",
  "var(--switch-sm-height)": "16px",
  "var(--switch-sm-checked-margin-left)": "-(13px)",
  "var(--switch-disabled-opacity)": "0.4",
  "var(--switch-color)": "#1890FF",
  "var(--switch-shadow-color)": "rgba(0, 35, 11, 0.2)",
  "var(--pagination-item-size)": "32px",
  "var(--pagination-item-size-sm)": "24px",
  "var(--pagination-font-family)": "Arial",
  "var(--pagination-font-weight-active)": "500",
  "var(--pagination-item-bg-active)": "#fff",
  "var(--page-header-padding)": "24px",
  "var(--page-header-padding-vertical)": "16px",
  "var(--page-header-padding-breadcrumb)": "12px",
  "var(--breadcrumb-base-color)": "rgba(0, 0, 0, 0.45)",
  "var(--breadcrumb-last-item-color)": "#000",
  "var(--breadcrumb-font-size)": "12px",
  "var(--breadcrumb-icon-font-size)": "12px",
  "var(--breadcrumb-link-color)": "rgba(0, 0, 0, 0.45)",
  "var(--breadcrumb-link-color-hover)": "#40a9ff",
  "var(--breadcrumb-separator-color)": "rgba(0, 0, 0, 0.45)",
  "var(--breadcrumb-separator-margin)": "0 8px",
  "var(--slider-margin)": "14px 6px 10px",
  "var(--slider-rail-background-color)": "#f5f5f5",
  "var(--slider-rail-background-color-hover)": "#e1e1e1",
  "var(--slider-track-background-color)": "#91d5ff",
  "var(--slider-track-background-color-hover)": "#69c0ff",
  "var(--slider-handle-border-width)": "2px",
  "var(--slider-handle-background-color)": "#fff",
  "var(--slider-handle-color)": "#91d5ff",
  "var(--slider-handle-color-hover)": "#69c0ff",
  "var(--slider-handle-color-focus)": "#46a6ff",
  "var(--slider-handle-color-focus-shadow)": "rgba(24, 144, 255, 0.2)",
  "var(--slider-handle-color-tooltip-open)": "#1890FF",
  "var(--slider-handle-shadow)": "0",
  "var(--slider-dot-border-color)": "#e8e8e8",
  "var(--slider-dot-border-color-active)": "#8cc8ff",
  "var(--slider-disabled-color)": "rgba(0, 0, 0, 0.25)",
  "var(--slider-disabled-background-color)": "#fff",
  "var(--tree-title-height)": "24px",
  "var(--tree-child-padding)": "18px",
  "var(--tree-directory-selected-color)": "#fff",
  "var(--tree-directory-selected-bg)": "#1890FF",
  "var(--tree-node-hover-bg)": "#e6f7ff",
  "var(--tree-node-selected-bg)": "#bae7ff",
  "var(--collapse-header-padding)": "12px 16px",
  "var(--collapse-header-padding-extra)": "40px",
  "var(--collapse-header-bg)": "#fff",
  "var(--collapse-content-padding)": "16px",
  "var(--collapse-content-bg)": "#fff",
  "var(--skeleton-color)": "#f2f2f2",
  "var(--transfer-header-height)": "40px",
  "var(--transfer-disabled-bg)": "#f5f5f5",
  "var(--transfer-list-height)": "200px",
  "var(--message-notice-content-padding)": "10px 16px",
  "var(--wave-animation-width)": "6px",
  "var(--alert-success-border-color)": "#b7eb8f",
  "var(--alert-success-bg-color)": "#f6ffed",
  "var(--alert-success-icon-color)": "#52c41a",
  "var(--alert-info-border-color)": "#91d5ff",
  "var(--alert-info-bg-color)": "#e6f7ff",
  "var(--alert-info-icon-color)": "#1890ff",
  "var(--alert-warning-border-color)": "#ffe58f",
  "var(--alert-warning-bg-color)": "#fffbe6",
  "var(--alert-warning-icon-color)": "#faad14",
  "var(--alert-error-border-color)": "#ffa39e",
  "var(--alert-error-bg-color)": "#fff1f0",
  "var(--alert-error-icon-color)": "#f5222d",
  "var(--list-header-background)": "transparent",
  "var(--list-footer-background)": "transparent",
  "var(--list-empty-text-padding)": "16px",
  "var(--list-item-padding)": "12px 0",
  "var(--list-item-meta-margin-bottom)": "16px",
  "var(--list-item-meta-avatar-margin-right)": "16px",
  "var(--list-item-meta-title-margin-bottom)": "12px",
  "var(--statistic-title-font-size)": "12px",
  "var(--statistic-content-font-size)": "24px",
  "var(--statistic-unit-font-size)": "16px",
  "var(--statistic-font-family)": "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', 'Helvetica Neue', Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'",
  "var(--drawer-header-padding)": "16px 24px",
  "var(--drawer-body-padding)": "24px",
  "var(--timeline-width)": "2px",
  "var(--timeline-color)": "#e8e8e8",
  "var(--timeline-dot-border-width)": "2px",
  "var(--timeline-dot-color)": "#1890FF",
  "var(--timeline-dot-bg)": "#fff",
  "var(--typography-title-font-weight)": "600",
  "var(--search-input-label-line-height)": "33px",
  "var(--search-input-padding-vertical)": "4px",
  "var(--search-input-padding-horizontal)": "11px",
  "var(--search-header-background)": "#fff",
  "var(--global-header-background)": "#fff",
  "var(--global-header-text-color)": "rgba(0, 0, 0, 0.8)",
  "var(--global-header-box-shadow)": "none",
  "var(--global-header-box-border-bottom)": "1px solid rgba(0, 0, 0, 0.1)",
  "var(--global-header-action-border-right)": "none",
  "var(--global-header-trigger-background)": "transparent",
  "var(--global-header-trigger-color)": "#000",
  "var(--header-hover-background)": "rgba(0, 0, 0, 0.1)",
  "var(--header-hover-color)": "#000",
  "var(--sider-menu-background)": "#001529",
  "var(--sider-menu-logo-box-shadow)": "none",
  "var(--sider-menu-logo-border-bottom)": "1px solid rgba(0, 0, 0, 0.1)",
  "var(--sider-menu-logo-color)": "rgba(0, 0, 0, 0.8)",
  "var(--sider-menu-logo-background)": "#001529",
  "var(--sider-menu-font-weight)": "normal",
  "var(--sider-menu-item-active-bg)": "rgba(0, 0, 0, 0.2)",
  "var(--sider-box-shadow)": "none",
  "var(--sider-border-right)": "1px solid rgba(0, 0, 0, 0.1)",
  "var(--card-box-shadow)": "none",
  "var(--card-border-radius)": "3px",
  "var(--card-border)": "1px solid rgba(0, 0, 0, 0.1)",
  "var(--ant-menu-sub-open-box-shadow)": "none",
  "var(--sider-menu-border-bottom)": "none",

  "var(--btn-default-bg)": "#fff",
  "var(--radio-button-bg)": "#fff",
  "var(--radio-button-checked-bg)": "#fff",
  "var(--btn-border-radius-base)": "20px",
  "var(--btn-border-radius-sm)": "12px",
  "var(--btn-shadow)": "0 1px 2px rgba(0,0,0,0.3)",
  "var(--btn-primary-shadow)": "0 1px 2px rgba(0,0,0,0.3)",
  "var(--btn-default-color)": "rgba(0, 0, 0, .65)",
  "var(--radio-button-color)": "rgba(0, 0, 0, .65)",
  "var(--btn-default-border-color)": "rgba(0,0,0,0.6)",
  "var(--global-header-background)": "#fff",
  "var(--global-header-text-color)": "#333",
  "var(--global-header-trigger-color)": "#333",
  "var(--sider-menu-logo-background)": "#fff",
  "var(--sider-menu-logo-color)": "#000",
  "var(--sider-menu-background)": "#fff",
  "var(--sider-menu-submenu-background)": "#fff",
  "var(--sider-menu-text-color)": "#000",
  "var(--global-header-box-shadow)": "0 2px 3px rgba(0,0,0,0.1)",
  "var(--global-header-box-border-bottom)": "none",
  "var(--sider-menu-logo-border-bottom)": "none",
  "var(--sider-menu-font-weight)": "bold",
  "var(--sider-box-shadow)": "2px 0 8px 0 rgba(29, 35, 41, 0.1)",
  "var(--sider-border-right)": "none",
  "var(--layout-header-background)": "#fff",
  "var(--layout-sider-background)": "#fff",
  "var(--menu-dark-bg)": "#fff",
  "var(--tint-layout-sider-background-10)": "#ffffff",
  "var(--card-box-shadow)": "0 0 5px rgba(0, 0, 0, 0.1)",
  "var(--card-border-radius)": "5px",
  "var(--card-border)": "none",
  "var(--form-vertical-label-padding)": "0px",
  "var(--ant-menu-sub-open-box-shadow)": "0 2px 10px rgba(0, 0, 0, 0.05) inset",
  "var(--search-header-background)": "linear-gradient(120deg, var(--primary-color) 1%, #fff 10%)",
  "var(--primary-color)": "#1890FF",
  "var(--antd-wave-shadow-color)": "#1890FF",
  "var(--primary-6)": "#1890ff",
  "var(--text-selection-bg)": "#1890FF",
  "var(--link-color)": "#1890FF",
  "var(--outline-color)": "#1890FF",
  "var(--btn-primary-color)": "#1890FF",
  "var(--checkbox-color)": "#1890FF",
  "var(--dropdown-selected-color)": "#1890FF",
  "var(--radio-dot-color)": "#1890FF",
  "var(--menu-highlight-color)": "#1890FF",
  "var(--menu-dark-item-active-bg)": "#1890FF",
  "var(--tabs-card-active-color)": "#1890FF",
  "var(--tabs-ink-bar-color)": "#1890FF",
  "var(--tabs-highlight-color)": "#1890FF",
  "var(--switch-color)": "#1890FF",
  "var(--slider-handle-color-tooltip-open)": "#1890FF",
  "var(--tree-directory-selected-bg)": "#1890FF",
  "var(--timeline-dot-color)": "#1890FF",
  "var(--fade-primary-color-20)": "rgba(24, 144, 255, 0.2)",
  "var(--slider-handle-color-focus-shadow)": "rgba(24, 144, 255, 0.2)",
  "var(--fade-radio-dot-color-6)": "rgba(24, 144, 255, 0.06)",
  "var(--fade-radio-dot-color-8)": "rgba(24, 144, 255, 0.08)",
  "var(--slider-handle-color-focus)": "#46a6ff",
  "var(--slider-dot-border-color-active)": "#8cc8ff",
  "var(--link-hover-color)": "#8cc8ff",
  "var(--primary-1)": "#e6f7ff",
  "var(--item-active-bg)": "#e6f7ff",
  "var(--item-hover-bg)": "#e6f7ff",
  "var(--table-row-hover-bg)": "#e6f7ff",
  "var(--select-item-active-bg)": "#e6f7ff",
  "var(--menu-item-active-bg)": "#e6f7ff",
  "var(--tree-node-hover-bg)": "#e6f7ff",
  "var(--primary-2)": "#bae7ff",
  "var(--tree-node-selected-bg)": "#bae7ff",
  "var(--primary-3)": "#91d5ff",
  "var(--slider-track-background-color)": "#91d5ff",
  "var(--slider-handle-color)": "#91d5ff",
  "var(--primary-4)": "#69c0ff",
  "var(--slider-track-background-color-hover)": "#69c0ff",
  "var(--slider-handle-color-hover)": "#69c0ff",
  "var(--primary-5)": "#40a9ff",
  "var(--btn-group-border)": "#40a9ff",
  "var(--radio-button-hover-color)": "#40a9ff",
  "var(--input-number-handler-hover-bg)": "#40a9ff",
  "var(--input-hover-border-color)": "#40a9ff",
  "var(--tabs-hover-color)": "#40a9ff",
  "var(--breadcrumb-link-color-hover)": "#40a9ff",
  "var(--primary-7)": "#096dd9",
  "var(--radio-button-active-color)": "#096dd9",
  "var(--tabs-active-color)": "#096dd9",
  "var(--link-active-color)": "#096dd9",
  "var(--primary-8)": "#0050b3",
  "var(--primary-9)": "#003a8c",
  "var(--primary-10)": "#002766",
}